# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-react-app-depl
# spec:
#   selector:
#     matchLabels:
#       app: react-app
#   replicas: 1    
#   template:
#     metadata:
#       labels:
#         app: react-app
#     spec:
#       containers:
#       - name: react-app
#         image: thilanka998/my-react-app:latest
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: <Port>

 
#  - - -

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-react-app-srv
# spec:
#   type: NodePort
#   selector:
#     app: react-app
#   ports:
#   - name: my-app
#     port: 3000
#     targetPort: 3000




apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-depl
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1    
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: thilanka998/my-react-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000  # Set the container port your React app is listening on


---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - name: my-app
    port: 80  # Expose the service on port 80
    targetPort: 3000  # Target the container port where your React app is running
